version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore ROS2 packages as they should be updated through rosdep
      - dependency-name: "rclpy"
      - dependency-name: "geometry_msgs"
      - dependency-name: "sensor_msgs"
