# .github/workflows/ros2-tests.yaml
name: ROS2 Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-pytest
        pip install pytest pytest-cov pytest-mock pytest-asyncio
        pip install catkin_pkg empy lark setuptools==58.2.0 colcon-common-extensions

    - name: Install ROS2 Humble
      run: |
        sudo apt update && sudo apt install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update
        sudo apt install -y ros-humble-ros-base

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-rosdep \
          python3-colcon-common-extensions \
          libunwind-dev
        
        # Initialize rosdep
        sudo rosdep init || true
        rosdep update

    - name: Install TurtleBot3 Dependencies
      run: |
        sudo apt install -y \
          ros-humble-dynamixel-sdk \
          ros-humble-turtlebot3-msgs \
          ros-humble-turtlebot3 \
          ros-humble-joy \
          ros-humble-joy-linux \
          ros-humble-teleop-twist-joy \
          ros-humble-teleop-twist-keyboard \
          ros-humble-geometry-msgs \
          ros-humble-sensor-msgs

    - name: Create workspace and build
      run: |
        mkdir -p ~/ros2_ws/src
        cp -r . ~/ros2_ws/src/xbox_turtlebot3_teleop
        cd ~/ros2_ws
        source /opt/ros/humble/setup.bash
        rosdep install --from-paths src --ignore-src -r -y
        colcon build --event-handlers console_direct+ --cmake-args -DCMAKE_BUILD_TYPE=Release
        
    - name: Run tests
      run: |
        cd ~/ros2_ws
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        colcon test --packages-select xbox_turtlebot3_teleop --event-handlers console_direct+
        colcon test-result --verbose
 
