name: ROS2 CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Python dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-flake8 python3-pytest python3-numpy
        python3 -m pip install --upgrade pip
        pip3 install numpy
        pip3 install black isort
        pip3 install catkin_pkg empy lark setuptools==58.2.0 colcon-common-extensions
        pip3 install pytest pytest-cov pytest-mock pytest-asyncio

    - name: Install ROS2 Humble
      run: |
        sudo apt update && sudo apt install -y curl gnupg2 lsb-release
        sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(source /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null
        sudo apt update
        sudo apt install -y ros-humble-ros-base python3-rosdep python3-numpy

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          python3-rosdep \
          libunwind-dev \
          python3-colcon-common-extensions \
          ros-humble-ros-base \
          python3-numpy

        sudo rosdep init || true
        rosdep update

    - name: Install TurtleBot3 Dependencies
      run: |
        sudo apt install -y \
          libgoogle-glog-dev \
          libceres-dev \
          liblua5.3-dev \
          python3-sphinx \
          python3-numpy \
          ros-humble-geometry-msgs \
          ros-humble-dynamixel-sdk \
          ros-humble-turtlebot3-msgs \
          ros-humble-turtlebot3-gazebo \
          ros-humble-navigation2 \
          ros-humble-nav2-bringup \
          ros-humble-slam-toolbox \
          ros-humble-joy \
          ros-humble-teleop-twist-joy \
          ros-humble-teleop-twist-keyboard

        sudo apt install -y \
          ros-humble-cartographer \
          ros-humble-cartographer-ros

    - name: Create ROS workspace
      run: |
        mkdir -p ~/ros2_ws/src
        cp -r . ~/ros2_ws/src/
        cd ~/ros2_ws
        source /opt/ros/humble/setup.bash
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build ROS2 workspace
      run: |
        cd ~/ros2_ws
        source /opt/ros/humble/setup.bash
        # Ensure numpy is available in the Python environment
        python3 -m pip install numpy
        colcon build --event-handlers console_direct+ --cmake-args -DCMAKE_BUILD_TYPE=Release

    - name: Run tests
      run: |
        cd ~/ros2_ws
        source /opt/ros/humble/setup.bash
        source install/setup.bash
        # Ensure numpy is available in the test environment
        python3 -m pip install numpy
        # Force reinstall numpy to ensure it's in the correct place
        python3 -m pip install --force-reinstall numpy
        colcon test --event-handlers console_direct+
        colcon test-result --verbose
